---
- hosts: kafkahosts
  become: true
  connection: ssh
  vars:
    - zookeeperinfo: nety-private.zk01.unipus-dev.com:2181,nety-private.zk02.unipus-dev.com:2181,nety-private.zk03.unipus-dev.com:2181/kafka1
    - dir_path: /data/kafka1-logs
  roles:
    - common
    - kafka