---
- hosts: zkhosts
  become: true
  connection: ssh
  vars:
    - brokerid: "{{ inventory_hostname | regex_search('(nety-private.zk0[1-9]\\.unipus-dev\\.com)') | regex_replace('\\.unipus-dev\\.com', '') | regex_replace('^nety-private.zk0', '') }}"
    - zookeeperinfo: nety-private.zk01.unipus-dev.com:2181,nety-private.zk02.unipus-dev.com:2181,nety-private.zk03.unipus-dev.com:2181/kafka2
    - dir_path: /data/kafka2-logs
  roles:
    - common
    - kafka