zookeeperversion: zookeeper-3.5.9
myid: "{{ inventory_hostname | regex_search('(nety-private.zk0[0-9]\\.unipus-dev\\.com)') | regex_replace('\\.unipus-dev\\.com', '') | regex_replace('^nety-private.zk0', '') }}"
dir_path: /data/zk