---
- name: install krb5
  yum:
    name: ['krb5-server', 'krb5-libs', 'krb5-workstation']
    state: latest

- name: copy kdc conf
  template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: copy krb5 conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: replace string
  replace:
    path: /var/kerberos/krb5kdc/kadm5.acl
    regexp: 'EXAMPLE.COM'
    replace: "{{ krb_realm }}"

- name: check principal exist
  stat:
    path: /var/kerberos/krb5kdc/principal
  register: stat_result

- name: create KDC database
  shell: kdb5_util create -r {{ krb_realm }} -P {{ kadmin_pass }} -s
  when: not stat_result.stat.exists

- name: create root
  shell: |
    kadmin.local -q "addprinc -pw {{ kadmin_pass }} root/admin"
    kadmin.local -q "add_principal -randkey nety-private.kafka01.unipus-dev.com@unipus-dev.com"
    kadmin.local -q "add_principal -randkey nety-private.kafka02.unipus-dev.com@unipus-dev.com"
    kadmin.local -q "add_principal -randkey nety-private.kafka03.unipus-dev.com@unipus-dev.com"
    kadmin.local -q "add_principal -randkey nety-private.zk01.unipus-dev.com@unipus-dev.com"
    kadmin.local -q "add_principal -randkey nety-private.zk02.unipus-dev.com@unipus-dev.com"
    kadmin.local -q "add_principal -randkey nety-private.zk03.unipus-dev.com@unipus-dev.com"

- name: make sure a service is running
  systemd:
    state: started
    name: "{{ item }}"
    enabled: yes
  with_items:
    - krb5kdc
    - kadmin